version: '3.8'

services:

  frontend:
    image: "${DOCKERHUB_USERNAME}/parto-frontend:latest"
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"


  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
